### ISSUE TITLE
Would be better if support with SvelteKIT ! 

### ISSUE THREAD

**Issue by tsrCodes** [thurti/svelte-prism-action#1]
Seems to there VITE warning when you use with sveltekit
Adding /* @vite-ignore */ comment inside import call could solve the warning problem !! But syntax highlighting doesn't working

**Comment by thurti** [comment]
I haven't used it with SvelteKit yet. I will have a look.

**Comment by tsrCodes** [comment]
@thurti Yes Thanks ! Do something ASAP !!! : )

**Comment by tsrCodes** [comment]
Thanks for updating the package !! : ) Works well
